### ISSUE TITLE
Website randomly goes down 

### ISSUE THREAD

**Issue by EricRabil** [dynasticdevelop/place#181]
Server Side
---
The issue is caused by an issue involving the canvas library.
```
Error: Batch is already running
  at /opt/old-place/node_modules/pajk-lwip/lib/BatchPrototypeInit.js:53:39
  at Object.exec (/opt/old-place/node_modules/decree/dist/cjs/decree.js:69:29)
  at Batch.exec (/opt/old-place/node_modules/pajk-lwip/lib/BatchPrototypeInit.js:52:16)
  at user.addPixel (/opt/old-place/util/PaintingManager.js:116:57)
  at /opt/old-place/models/user.js:242:20
  at /opt/old-place/node_modules/mongoose/lib/model.js:3800:16
  at /opt/old-place/node_modules/mongoose/lib/services/model/applyHooks.js:150:20
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)
```
It seems to be triggered when a user places a pixel while the server is still processing a previous pixel placement.

Client Side
---
The board-image will randomly return 503 at times.
```
[Error] Failed to load resource: the server responded with a status of 503 (HTTP/2.0 503) (board-image, line 0)
```
Users will get stuck on the following screen:
![screen shot 2017-07-24 at 6 43 45 pm](https://user-images.githubusercontent.com/8052613/28548191-9ac3b330-70a0-11e7-925d-a45f68893d74.png)

**Comment by AppleBetas** [comment]
Fixed by 07b3952
