### ISSUE TITLE
Could not locate the bindings file.

### ISSUE THREAD

**Issue by Jengas** [dynasticdevelop/place#249]
After doing all by instruction, I have this error when trying to launch script

```
C:\Users\Jengas\Desktop\Canval Place\place>node app.js
C:\Users\Jengas\Desktop\Canval Place\place\node_modules\bindings\bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\build\lwip_image.node
 → C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\build\Debug\lwip_image.node
 → C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\build\Release\lwip_image.node
 → C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\out\Debug\lwip_image.node
 → C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\Debug\lwip_image.node
 → C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\out\Release\lwip_image.node
 → C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\Release\lwip_image.node
 → C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\build\default\lwip_image.node
 → C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\compiled\10.1.0\win32\x64\lwip_image.node
    at bindings (C:\Users\Jengas\Desktop\Canval Place\place\node_modules\bindings\bindings.js:93:9)
    at C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\lib\Image.js:3:41
    at Object.<anonymous> (C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\lib\Image.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\lib\ImagePrototypeInit.js:3:17
    at Object.<anonymous> (C:\Users\Jengas\Desktop\Canval Place\place\node_modules\pajk-lwip\lib\ImagePrototypeInit.js:620:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
```

**Comment by nullpixel** [comment]
did you definitely run `npm I`?

**Comment by Jengas** [comment]
@nullpixel i used yarn install, how it was told in the instructions

**Comment by nullpixel** [comment]
Yeah. This is *really* strange; you might be better starting over and trying again.

**Comment by Jengas** [comment]
@nullpixel i have tried more that 5 times. Using different versions of node. Sush as v10 and v8. But nothing at all. Google error didn't help much, even intalling some global modules didn't help at all

**Comment by AppleBetas** [comment]
This issue is a configuration/`node-gyp` issue and should be treated as such. As a result, it is not an appropriate issue for the Place GitHub project. Feel free to message me on the Discord if you want to try and work this out.

Thanks for your interest in using and improving Place.
