### ISSUE TITLE
Updated to incompatible mongoose version

### ISSUE THREAD

**Issue by mro95** [dynasticdevelop/place#269]
When i try to start the app with docker-compose up I get this error.

```
api_1  | yarn run v1.21.1
api_1  | warning package.json: License should be a valid SPDX license expression
api_1  | $ node app.js
api_1  | --------- [ MESSAGES ON 2020-4-25 ] ---------
api_1  | 15:16:20 [CHANGELOGS] INFO: Starting load of changelogs…
api_1  | 15:16:20 [MODULE MANAGER] LOG: Starting load of modules…
api_1  | 15:16:20 [STARTUP] INFO: Loading image from the database…
api_1  | 15:16:20 [LEADERBOARD] LOG: Starting generation of leaderboard data…
api_1  | /usr/src/app/node_modules/mquery/lib/collection/node.js:131
api_1  |   return this.collection.find(match, findOptions).stream(streamOptions);
api_1  |                                                   ^
api_1  |
api_1  | TypeError: this.collection.find(...).stream is not a function
api_1  |     at NodeCollection.findStream (/usr/src/app/node_modules/mquery/lib/collection/node.js:131:51)
api_1  |     at model.Query.Query.stream (/usr/src/app/node_modules/mquery/lib/mquery.js:3016:27)
api_1  |     at Object.update (/usr/src/app/util/LeaderboardManager.js:20:80)
api_1  |     at LeaderboardManager (/usr/src/app/util/LeaderboardManager.js:67:13)
api_1  |     at Object.<anonymous> (/usr/src/app/app.js:72:26)
api_1  |     at Module._compile (module.js:653:30)
api_1  |     at Object.Module._extensions..js (module.js:664:10)
api_1  |     at Module.load (module.js:566:32)
api_1  |     at tryModuleLoad (module.js:506:12)
api_1  |     at Function.Module._load (module.js:498:3)
api_1  |     at Function.Module.runMain (module.js:694:10)
api_1  |     at startup (bootstrap_node.js:204:16)
api_1  |     at bootstrap_node.js:625:3
api_1  | error Command failed with exit code 1.
```

I try to play around with it but nothing seems to work.

**Comment by nullpixel** [comment]
You need to install the correct version of mongoose. Iirc it’s v4 or 5, but you’ll need to test to find out what that is. Sorry about that.

**Comment by andreybutenko** [comment]
@mro95: I was able to fix this issue by running `yarn upgrade mongoose@legacy`
