### ISSUE TITLE
Disabling captcha reveals error on user creation

### ISSUE THREAD

**Issue by tilda** [dynasticdevelop/place#87]
I'm not sure that captcha is the issue, but I think it is.

```
TypeError: Cannot read property 'verify' of undefined
    at /home/s/place/routes/public.js:28:22
    at Layer.handle [as handle_request] (/home/s/place/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/s/place/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/s/place/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/s/place/node_modules/express/lib/router/layer.js:95:5)
    at /home/s/place/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/s/place/node_modules/express/lib/router/index.js:335:12)
    at next (/home/s/place/node_modules/express/lib/router/index.js:275:10)
    at /home/s/place/routes/public.js:16:73
    at Layer.handle [as handle_request] (/home/s/place/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/s/place/node_modules/express/lib/router/index.js:317:13)
    at /home/s/place/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/s/place/node_modules/express/lib/router/index.js:335:12)
    at next (/home/s/place/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/s/place/node_modules/express/lib/router/index.js:174:3)
    at router (/home/s/place/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/s/place/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/s/place/node_modules/express/lib/router/index.js:317:13)
    at /home/s/place/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/s/place/node_modules/express/lib/router/index.js:335:12)
    at next (/home/s/place/node_modules/express/lib/router/index.js:275:10)
    at User.findById.then.user (/home/s/place/util/HTTPServer.js:57:17)
```

Authentication method was GitHub.

**Comment by AppleBetas** [comment]
Can confirm that this does indeed happen
